services:
  messenger-api:
    build:
      context: ./backend        # 👈 Указываем папку, где лежит .sln
      dockerfile: ./Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=messengerdb;Username=postgres;Password=postgres

  db:
    image: postgres:15
    container_name: messenger-db
    restart: always
    environment:
      POSTGRES_DB: messengerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
