version: "3.8"

services:
  # ———————— база ----------------
  db:
    image: postgres:15
    container_name: messenger-db
    restart: always
    environment:
      POSTGRES_DB: messengerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ———————— API (.NET) ----------------
  messenger-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: messenger-api
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      ASPNETCORE_URLS: http://+:80;https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERT_PASSWORD}
    ports:
      - "5002:80"    # HTTP
      - "5003:443"   # HTTPS
    volumes:
      # ваш PFX-файл лежит в frontend/certs
      - ./frontend/certs:/https:ro

  # ———————— Фронт (Vite + Vue) ----------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: savranimessenger-frontend
    depends_on:
      - messenger-api
    env_file:
      - ./.env
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      CERT_PASSWORD:        ${CERT_PASSWORD}
    ports:
      - "5173:5173"
    volumes:
      # Монтируем всю папку frontend в /app, 
      # чтобы контейнер «видел» именно ваши файлы
      - ./frontend:/app
      # node_modules оставляем в контейнере, 
      # чтобы не затирать при монтировании
      - /app/node_modules

volumes:
  pgdata:
