version: "3.8"

services:
  db:
    image: postgres:15
    container_name: messenger-db
    restart: always
    environment:
      POSTGRES_DB: messengerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  messenger-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: messenger-api
    depends_on:
      - db
    ports:
      - "5002:80"    # HTTP
      - "5003:443"   # HTTPS
    env_file:
      - ./.env
    environment:
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
    volumes:
      - ./frontend/certs:/https:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: savranimessenger-frontend
    depends_on:
      - messenger-api
    ports:
      - "5173:5173"
    env_file:
      - ./.env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - CERT_PASSWORD=${CERT_PASSWORD}
    # монтируем локальную папку с сертификатом в контейнере
    volumes:
      - ./frontend/certs:/app/certs:ro

volumes:
  pgdata:
