services:
  messenger-api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_CONTAINER_PORT}"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_HOST};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    command: ["./wait-for-it.sh", "${POSTGRES_HOST}:5432", "--", "dotnet", "Messenger.API.dll"]

  db:
    image: postgres:15
    container_name: messenger-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_CONTAINER_PORT}"
    depends_on:
      - messenger-api

volumes:
  pgdata:
